### ISSUE TITLE
Compile error when compiling with clang/gcc

### ISSUE THREAD

**Issue by ceeac** [phisko/kengine#6]
```
third_party/kengine/EntityManager.hpp:3:10: fatal error: 'execution' file not found
#include <execution>
         ^~~~~~~~~~~
1 error generated.
```
The latest versions of both libc++ and libstdc++ do not include this header yet, so kengine cannot be compiled with GCC or Clang at the moment.

**Comment by phisko** [comment]
Darn, that's a recent addition to the engine that I haven't tested on other platforms yet. I'll disable those conditionally when I get the chance, thanks.
